<?xml version="1.0"?>
<package format="2">

  <name>tuw_iwos</name>
  <version>1.0.0</version>
  <description>Tools for independent wheel offset steering.</description>

  <maintainer email="eugen.kaltenegger@gmail.com">Eugen Kaltenegger</maintainer>

  <license>BSD</license>

  <author email="eugen.kaltenegger@gmail.com">Eugen Kaltenegger</author>

  <doc_depend>python3-sphinx</doc_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
