<?xml version="1.0"?>
<package format="2">
  <name>tuw_iwos_hardware</name>
  <version>1.0.0</version>
  <description>Package to operate IWOS hardware</description>

  <maintainer email="eugen.kaltenegger@gmail.com">Eugen Kaltenegger</maintainer>

  <license>BSD</license>

  <author email="eugen.kaltenegger@gmail.com">Eugen Kaltenegger</author>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rospy</depend>
  <depend>roslint</depend>
  <depend>combined_robot_hw</depend>
  <depend>controller_manager</depend>

  <exec_depend>tuw_hardware_interface_dynamixel</exec_depend>
  <exec_depend>tuw_hardware_interface_trinamic</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <!-- nothing to export -->
    <build_type>ament_cmake</build_type>
  </export>

</package>
