controller_manager:
  ros__parameters:
    update_rate: 60

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_control:
  ros__parameters:
    type: one_joint_position_controller/OneJointPositionController

    joint: "steering_right"

# placeholder_controller:
  # ros__parameters:
    # type: diff_drive_controller/DiffDriveController
